### ISSUE TITLE
Dcoder Admiration

### ISSUE THREAD

**Issue by prthmptl** [Aimnos/Dcoder-Challenges#3]
Hello Aimnos,

Can you pls explain me the problem statement of the problem "Dcoder Admiration"?

**Comment by Aimnos** [comment]
Sure.
"Dcoder has N members each numbered from 1 to N. A member admires other member if its number divides the other member's number. Given a number N you need to find the number of people with odd number of admirers"

So, given a number N, assume that there are N people in a conference of some kind. They are numbered from 1 to N.
Member A admires member B if A's number is a factor of B's number. For example, the member with the number 12 has 5 admirers: members 1, 2, 3, 4 and 6.
As such, every member has the number of admirers equal to its number's unique factors, except for itself (the unique factors of 12 are 1, 2, 3, 4, 6 and 12).

**Comment by prathpatel** [comment]
> Sure.
> 
> "Dcoder has N members each numbered from 1 to N. A member admires other member if its number divides the other member's number. Given a number N you need to find the number of people with odd number of admirers"
> 
> 
> 
> So, given a number N, assume that there are N people in a conference of some kind. They are numbered from 1 to N.
> 
> Member A admires member B if A's number is a factor of B's number. For example, the member with the number 12 has 5 admirers: members 1, 2, 3, 4 and 6.
> 
> As such, every member has the number of admirers equal to its number's unique factors, except for itself (the unique factors of 12 are 1, 2, 3, 4, 6 and 12).

So, according to you the answer to input 12 should be 6, right?

**Comment by Aimnos** [comment]
> So, according to you the answer to input 12 should be 6, right?

Nope. As I stated previously:

> For example, the member with the number 12 has 5 admirers: members 1, 2, 3, 4 and 6.

and

> As such, every member has the number of admirers equal to its number's unique factors, except for itself (the unique factors of 12 are 1, 2, 3, 4, 6 and 12).

6 is neither the amount of admirers that member 12 has nor the answer to input 12.
Member 12 has 5 admirers, because that's how many unique factors 12 has, except for itself.
The answer for input 12 should be 9, because out of all the members numbered from 1 to 12, exactly 9 of them have odd admirers, which is what the statement asks for: "Given a number N you need to find the number of people with odd number of admirers".
